### ISSUE TITLE
Use computed properties for DOM Element class bindings

### ISSUE THREAD

**Issue by griest024** [stasson/vue-mdc-adapter#111]
The Situation
---------------

The current design pattern in this codebase to dynamically set classes on a DOM element is to return an object containing the classes in the `data` property function. It must be in `data` because the foundation must be able to add and remove classes and you can't modify `props` internally.

The Problem
--------------

However keeping all of the classes in `data` presents a problem. All of the classes are generated at component creation (depending on the value of the associated `props`) but the `data` class object won't change in response to changes in `props` after component creation.

I would argue that this defeats the purpose of using a reactive framework like Vue. None of the components can react to changes in the external environment.

If you don't agree that it would be a good thing to have reactive components let me state an example: **dynamically disabling a `textfield`**.

Let's say that you want to disable a `textfield` until the user fulfills some condition:

```vue
<template>
  <mdc-textfield :disabled="textfieldDisabled"></mdc-textfield>
</template>

<script>
export default {
  computed () {
    textfieldDisabled () {
      // check if the user has fulfilled some condition
    }
  }
}
</script>
```

Even when the user fulfills the condition and `textfieldDisabled` and `disabled` are `false`, the textfield will still be disabled because the class on the element won't change in response to the `disabled` prop.

The Solution
--------------

Use `computed` properties. By binding the element's properties to a `computed` property, it can react to changes in the external environment. However, the element also needs to be able to react to changes in the internal environment, i.e. changes by the foundation. To handle this, we should have both `computed` and `data` properties for an element's class.

So instead of this:

```vue
<div :class="rootClasses">...</div>

...

<script>
export default {
  data () {
    return {
      rootClasses: {
        'mdc-text-field--disabled': this.disabled
      }
    }
  }
}
</script>
```

We should do this:

```vue
<div :class="rootElementClasses">...</div>

...

<script>
export default {
  computed () {
    return {
      rootElementClasses: {
        'mdc-text-field--disabled': this.disabled,
        ...this.rootClasses // this is where the internal changes by the foundation are included
      }
    }
  },
  data () {
    return {
      rootClasses: {}
    }
  }
}
</script>
```

The reactive behavior of many components depends on the ability to change classes on DOM elements in response to `props`.

**Comment by stasson** [comment]
@griest024 

- I understand what a computed property is. 
- I agree disabled should be reactive. 
- And I agree right now there is a bug, I didn't refactor textfield to watch for disabled prop

Don't agree with the solution though. We have to take MDC foundation patterns as well here we need to watch the disabled prop and call foundation.setDisable... 
Also need to check I didn't do the same mistake for other components.

**Comment by griest024** [comment]
@stasson what MDC patterns are destroyed by my solution?

Are you saying that any reactive behavior that we might want in a component can be achieved through interaction with the foundation?

**Comment by stasson** [comment]
@griest024 

Not really. what I'm saying is that it should a be case by case decision and it's difficult to find a design pastern that works for all cases. For the text field disable property case , we have to take into account foundation design. For this case, the easiest and straightforward way is to watch the disable property and dispatch to `setDisable`. Any other way I figured seems more more complex or problematic. 

So the pattern you are proposing is ideally the right one, but practically, we need to take into account performance and MDC design into account on a case by case basis.

My take on this: as a general rule 
- Some properties must be reactive (disable is a perfect example.) Then we use generic Vue way, if compatible with MDC foundation way. otherwise we figure out something else.
- Some property do not need to be dynamic (an example is initializers attributes, for which it may not make sense to be changed after initialization: the textfield multiple property.) Dynamic properties have a performance cost, so if we can avoid it, let's try...

Note that for this specific case 
```javascript 
rootClasses: {
        'mdc-text-field--disabled': this.disabled
      }
```
Here I'm just initializing classes and the value should be changed later by the adapter depending on foundation state.
