### ISSUE TITLE
Make drawer items appear "clickable"

### ISSUE THREAD

**Issue by griest024** [stasson/vue-mdc-adapter#124]
If no `href` is specified for a `mdc-drawer-item` then when hovering over the item, the cursor will not change to "click" mode.

<details><summary>Cursors</summary>
<figure>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Mouse-cursor-hand-pointer.svg/1200px-Mouse-cursor-hand-pointer.svg.png" />
<figcaption>The normal cursor is on the left and the "click" cursor is on the right</figcaption>
</figure>
</details>

**Comment by stasson** [comment]
The issue with the  href=# solution is that it doesn't interact well with vue-router: 

You can see it in the demo site the window.location is always `#` with the change.
That's why I did remove default href prop. Now I agree this doesn't solve the issue that the cursor is wrong when hovering. Probably better better to force the behaviour from sass and keep the href optional for now... until we can have better router-link integration strategy #90

**Comment by griest024** [comment]
the style we need is `cursor: pointer`.

**Comment by griest024** [comment]
@stasson you want project-wide css rules in `components/styles.scss` right?
