### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by griest024** [stasson/vue-mdc-adapter#131]
It would be nice to define and follow a consistent style in the project. I think the [official Vue style guide](https://vuejs.org/v2/style-guide/) priorities A and B is a good place to start.

Some of the changes that would come from this would be [defining prop names in camelCase](https://vuejs.org/v2/style-guide/#Prop-name-casing-strongly-recommended) and [putting one html attribute per line](https://vuejs.org/v2/style-guide/#Multi-attribute-elements-strongly-recommended).

In addition to the Vue priority A and B rules I propose the following:

- End files with a newline
- The order of sections in single file components should be template, script, style.
- 2 blank lines between different sections of different types in single file components and 1 blank line between sections of the same type (like 2 style sections)
- When importing a `.js` or `.vue` file, omit the extension

I would be happy to set up linting and change the existing codebase to conform to the style guide so feel free to assign this to me.

**Comment by griest024** [comment]
As for the html attribute per line, which do you prefer?

1.
```
<tag
  attr0
  attr1
  >content</tag>

<self-closing-tag
  attr0
  attr1
  />
```

2.
```
<tag
  attr0
  attr1
>content</tag>

<self-closing-tag
  attr0
  attr1
/>
```

3.
```
<tag
  attr0
  attr1 >
  content</tag>

<self-closing-tag
  attr0
  attr1 />
```

**Comment by stasson** [comment]
@griest024 

You are assigned but let's agree on the rules first. code standard vs quality is a very sensitive subject so let's agree on the rule first

**Comment by stasson** [comment]
@griest024 

Here is what I think : 

Readability is very subjective.  I have seen so many projects where for the sake of readability, there were so many rules enforced that it would take a huge extra efforts to code and that the inspection wouldn't go through because one guy didn't agree with the name of a variable. If you have ever worked with linux kernel guys you will understand how crazy code style enforcing can become. 

Process has to stay light and to not constrain the developer. Code quality comes after feature set and test/code coverage. for now the project mostly lacks of test spec and we should take code standard with a lesser priority vs test.spec. 

That being said, I know code standard matters a lot: 
1. issue avoidance ( build env requirements, confusions etc...)
1. readability/community alignment

I came up with a simple lightweight scheme at work with my teams:

- 2 rule categories  1) Enforced rules 2) Guidelines

- Enforced rules are about issue avoidance (build env requirements, bug avoidance). CI should fail the build if not compliant. development builds should not fail, just raise warnings
- Guidelines are not enforced and and do not block a merge, they are just captured at inspection time or or tracked as warnings from the CI. 
- when implementing rules  on an existing project, do it progressively : 
  - few rules at a time
  - new code first, old code being is done through step by step refactoring.
 
so there are two kinds of coding style rules: 
- category A: the one we want to enforce: should be enforced through linter so that the CI can reject it. *There should be as less as possible of enforced rules* to avoid blocking an issue just for the sake of style 
- category B: the guidelines:  all the other one which will only be recommendations. should not block the merge. eventually we can lint them as warning and. 0 warnings being achieved through later refactoring (may be tracked on codacy ?)

the way we should proceed : 
1. Define the enforced vs guidelines rules and document them in `CONTRIBUTING.md`
1. One branch for each enforced rule. if fixing the rule requires non-trivial code change, create an exception and open an issue to track.
1. fix open issue
1. (optional) put in place warnings for the guidelines category

**Comment by stasson** [comment]
Also we should only enforce on code that ship
- so filter on ./components/*
- exclude demo.* test.spec.*

**Comment by stasson** [comment]
I guess we can start with that:

## Baseline : 
eslint/stylelint : recommended rules

use <https://www.npmjs.com/package/eslint-plugin-vue> to add .vue rules

> regarding the  putting one html attribute per line, I actually do not agree, it doesn't really help readbility as it's much less compact and you do not see the overall structure. I may want to group attributes on the same line :
```html
<component is="router-link"
  :class="classes" :style="styles"
  v-for="folder in folders" :key="index"
  :to="folder.name" append
>{{folder.displayName}}</component>
```
Although having no spaces arround the html content is error prevention and should probably be enforced:

```html
<tag :class="classes" :style="styles"
 >{{message}}</tag>
```

```html
<tag :class="classes" :style="styles"
 >Lorem Ipsum is simply dummy text of the printing and typesetting industry.
Lorem Ipsum has been the industry's</tag>
```




I'd go for 2) 

## Enforced rules: 

### Priority-A: [Essential-Error-Prevention](https://vuejs.org/v2/style-guide/#Priority-A-Rules-Essential-Error-Prevention)

> All priority A rules but for [style scoping](https://vuejs.org/v2/style-guide/#Component-style-scoping-essential) where we have to do global styles in sass (cause MDC is sass framework)

### vue-mdc-adapter specific rules 
#### SFC Sections
- SFC sections should be template, script with no attributes
- SFC should not have a <style> element. (build env requirement to avoid issues with sass: stylesheet goes to style.scss)
- SFC template section has no attributes (=>html).
- SFC script section has no attributes (=> es6)

#### Distributed Plugins 
- distributed package default export valid Vue plugin (valid install function)
- distributed package default export is a valid Vue mixin (components/directives/filters)
- filepath components/[plugin]/*

#### Distributed Components
- filepath components/[plugin]/mdc-xxx-yyy.(vue|js)
- has a name field which matches `/mdc-xxx-yyy/`
- has a static class which matches component name exactly
- data is a function
- provide is a function
- MDC adapters match __exactly__ the MDC API 

there are some rules I am already enforcing through unit test [sanity checks](https://github.com/stasson/vue-mdc-adapter/blob/bd700bfa180e5fe1ce71e156424e414eacd34228/components/test-utils/index.js#L6):
 
I guess it's better to enforce at lint time, but unit test is a nice fallback. 

## Guidelines

All other rules should not be enforced.

**Comment by griest024** [comment]
@stasson You're right, the style guide should not constrain the development process, but rather enable it by promoting readability and reducing bugs.

With that said, I do really like the idea of putting a single HTML attribute per line. Currently with multiple attributes per line, its not immediately obvious exactly which attributes are being set on that element. I have to read every single line of the element before I can be sure which props are being assigned. Its the same idea as with a JS object: with only one property per line its easy to see exactly what properties the object has.

```js
{
  prop0: test.getThing(arg0, arg1), other: wowThisNameIsTooLong,
  prop1: 5
}
```

It's easy to lose the `other` property amongst the chaos of the `prop0`'s value.
