### ISSUE TITLE
Ripple effects restore too slowly

### ISSUE THREAD

**Issue by skyne98** [stasson/vue-mdc-adapter#241]
After issuing the ripple effect, it restores to the initial state too slowly, blocking the whole effect.

Is there a solution? It doesn't seem like a browser-specific bug.

**Comment by stasson** [comment]
@skyne98 

can you attach pen or details on how to reproduce plz ?

**Comment by skyne98** [comment]
@stasson 
There is actually no need to, it works like this for me in the official docs.

**Vue MDC**
![peek 2018-02-09 18-08](https://user-images.githubusercontent.com/4999658/36040014-7e38e2c8-0dc4-11e8-9b9c-aece18b222af.gif)
**Official MDC**
![peek 2018-02-09 18-09](https://user-images.githubusercontent.com/4999658/36040015-7e5ef530-0dc4-11e8-90c9-ef8287e70893.gif)

**Comment by stasson** [comment]
@skyne98 

Ok. this because I'm using vue class binding which caches changes to DOM (see [Vue Async-Update-Queue](https://vuejs.org/v2/guide/reactivity.html#Async-Update-Queue) [Ripple's addClass()](https://github.com/stasson/vue-mdc-adapter/blob/master/components/ripple/mdc-ripple-base.js#L30). 

This is actually a behavior I kind of like, keeping the effect on instead of resetting it at every click...
I'd like to keep it this way, unless it creates an issue... I'd like to keep the implementation simple if possible... 

let me know what you think

**Comment by skyne98** [comment]
@stasson I appreciate the work you've done a lot, guys, as your implementation seems to be the most usable and stable one. However, this library is called **vue-mdc-adapter**, and I am sure, that everyone who finds it online would expect it to be as close as possible to the original **mdc**.
If your goal is not to wrap the existing framework/library, but to create something bigger on top of it (which might be super awesome too), you might have to think about a different name.

**Comment by stasson** [comment]
@skyne98 

ok see your point.

- __vuetify__: MDC full feature framework
- __material-component-vue__: wrapping vanilla mdc, as close as possible to mdc
-  __vue-mdc-adapter__: Foundadtion/Adapter based implementation of MDC following vue spirit (Approachable, Versatile, Performant)

I plan to go some day for something more ambitious but that would be another project. need to finalize a first stable version of this one first. 

As of today, the goal is to be as close as mdc with couple of exceptions:

1. Components have to be Aproachable, they should work out of the box, so I reserve the right to modify vanilla MDC behaviors in order to workarround bugs or add some obvious missing features.

2. I have to balance performance and complexity of the baseline, mostly because I have a limited bandwidth  to work on the project.

Coming back to the ripple implementation issue: I still think MDC behavior is wrong with regard to UI/UX here. But I'm ok with aligning the behavior with mdc, although it's not straight forward and I have to focus on keeping up with new MDC releases for now. so I'll keep the issue open and try to adress it asap...

**Comment by rustemgareev** [comment]
1. vuetify is not an MDC-Web based project.
2. Vue MDC Adapter is not as versatile as it tries to be. Most of the time it's based on simple MDC-Web demos without considering more complex and advanced use cases.
3. Vue MDC Adapter adds opinionated elements, which:
- are not presented in MDC-Web
- add more complexity for maintainence rather than "feature richness".
For instance, let's take a drawer-list and drawer-list-item. It can be done with MDC List, refactored for flexibility and versatility. Adding a one more element with duplicate functionality requires updating the code in [one](https://github.com/stasson/vue-mdc-adapter/issues/203) [more](https://github.com/stasson/vue-mdc-adapter/issues/247) [place](https://github.com/stasson/vue-mdc-adapter/issues/240).

**Comment by stasson** [comment]
@rustemgareev 

No need to take it like that! I was just trying to explain my position and:
- Why I think _vue-mdc-adapter_ is still a fitting name (the goal is still wrap MDC with vue components following the adapter way,)
- That I'll try to stay as close as MDC vanilla as possible (but there are a few exceptions,)
- That I'm OK to keep this change request open,  but implementation (adapter way) is not straightforward as it looks and I'll do it once I'm done with the MDCWeb rebase and other high priority features. 

Regarding the other points, yes vue-mdc-adaper is opiniated, both in the design and how I deal with complexity, maintainability and reusablilty. I think this better be discussed on gitter rather than in this thread though.

**Comment by stasson** [comment]
outdated

**Comment by MioQuispe** [comment]
Bleh! looks like I'll have to ditch this then.

**Comment by ashrafhadden** [comment]
Just submitted a PR #533 

## The Fix
1. Assuming you've installed the latest [vue-mdc-adapter](https://www.npmjs.com/package/vue-mdc-adapter),
go to `node_modules/vue-mdc-adapter/dist/ripple/index.js`
2. `Cmd + F` on your page to find `vm.$set(vm.classes, className, true)`, around line 1300 on mine (v0.18.2)
3. Replace `addClass` and `removeClass` functions with these:
```js
      addClass: function addClass(className) {
        vm.$el.classList.add(className)
        vm.$set(vm.classes, className, true)
      },
      removeClass: function removeClass(className, target) {
        vm.$el.classList.remove(className)
        vm.$delete(vm.classes, className)
      },
```
4. Profit
