### ISSUE TITLE
How to make Checkbox (JS version) from original mdc?

### ISSUE THREAD

**Issue by jerakode** [stasson/vue-mdc-adapter#25]
Hi. I don't see in demo this version (on the buttom) - https://material-components-web.appspot.com/checkbox.html

Also wonder, is this lib compatible with SSR, Nuxt?

**Comment by stasson** [comment]
@jerakode 

Hi, 

* regarding the checkbox, you have the demo @ [input-controls](https://stasson.github.io/vue-mdc-adapter/#input-controls) , although the ripple effect is not working yet and I have not added the indeterminate style yet.

* regarding SSR and Nuxt, I'm not an expert. In theory everything should work but the mdc-v-ripple directive. componnents should be ok as far as I understand, but I may have missed something from the doc. Did you try it ?

**Comment by stasson** [comment]
```html
<mdc-checkbox  label="A Checkbox" v-model="isChecked"></mdc-checkbox>
```

```javascript
var vm = new Vue({
  data: {
    isChecked: true
  }
})
```

**Comment by stasson** [comment]
I have added indeterminate prop and the ripple 
https://github.com/stasson/vue-mdc-adapter/tree/master/src/components/checkbox

[input-controls](https://stasson.github.io/vue-mdc-adapter/#input-controls)

**Comment by jerakode** [comment]
I don't know why, but Nuxt even doen't see this package

```
This dependency was not found:

To install it, you can run: npm install --save vue-mdc-adapter

```

**Comment by jerakode** [comment]
Hey. There's a little bug in https://github.com/stasson/vue-mdc-adapter/blob/master/package.json#L15 - https://github.com/nuxt/nuxt.js/issues/917#issuecomment-309280051

AND THANKS for awesome package! It's working!

**Comment by jerakode** [comment]
Also wonder, will Radio will also be upradeted with ripple feature?

**Comment by jerakode** [comment]
Unfortunately, got errors SSR-related. As always. SSR is nightmare. 

![damn](https://user-images.githubusercontent.com/29287093/27262728-f10d70d8-542a-11e7-9c9d-72d80b298708.png)

**Comment by jerakode** [comment]
Sorry again, I fixed it for SSR. If curious:

```
<template>
  <section class="container">
    <div>
      <mdc-checkbox v-if="isChecked" label="A Checkbox"></mdc-checkbox>
    </div>
          <div class="doc-center">
            <mdc-radio v-if="isRadio" label="Radio1" name="radios" value="radio1" v-model="picked" checked></mdc-radio>
            <mdc-radio v-if="isRadio" label="Radio2" name="radios" value="radio2" v-model="picked"></mdc-radio>
            <p>{{ picked }}</p>
            <p><br></p>
          </div>
  </section>
</template>

<script>

export default {
  data () {
    return {
      isChecked: false,
      isRadio: false,
      picked: null
    }
  },
  mounted () {
    this.isChecked = true
    this.isRadio = true
  }
}
</script>
```
No SSR errors! Beautiful!

@stasson this package is awesome. 
How can I contribute?

**Comment by stasson** [comment]
@jerakode 

> Thanks to nuxt/nuxt.js#917 (comment)

Nice finding and thanks for letting me know! I have open #27 for this bug.


> Also wonder, will Radio will also be upgraded with ripple feature?

Yes, I plan to support same javascript features and ripples as MDC vanilla components. Radio was not my priority yet ( I have lot of work to do with finalizing api's and bundling ...) But if you need it I'll try to do it within the next couple of weeks.

> How can I contribute?

I'll welcome any help. I you find bugs or feature improvements don't hesitate to open issues or submit pull request. The way that I work is as follow: I usually review and decide if I merge directly or if it needs some rework. I have started a wiki](https://github.com/stasson/vue-mdc-adapter/wiki) to put roadmap and contribution infos. 

Right now I'm still in development phase so the APIs ( props events and slots ) may change significantly. Also I'm not fully satisfied with the bundling and demo site so this will probably change as well. I'm explaining that so that you don't get upset when I'm doing breaking changes. Once we reach beta I'll freeze the APIs and it will be easier for everyone.

Also, as you know how to use nuxt and ssr, may be you could help there. I have started to read the nuxt doc and it seems you can generate static sites with nuxt. May be we could use nuxt to generate the demo and doc site? would you agree to help with that ?

**Comment by jerakode** [comment]
@stasson sure, I can help with that. I just tried to generate static site with Nuxt and vue-mdc-adapter - worked just fine, http://unwieldy-stream.surge.sh/

Had one webpack caution 

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (300 kB).
This can impact web performance.
Assets: 
  nuxt.bundle.1f5672929109b4eef126.js (387 kB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (300 kB). This can impact web performance.
Entrypoints:
  app (657 kB)
      manifest.77715a711fb590abe21a.js
      vendor.bundle.0406979ce3c26b14ca89.js
      nuxt.bundle.1f5672929109b4eef126.js
```
But I think it can be solved in future. 

As for Radio - I am not hurry you up, do what you consider priority!

**Comment by jerakode** [comment]
@stasson we can easily copy MDC https://material-components-web.appspot.com/card.html
And it will be even better due to Nuxt SPA UX. 
Will be happy to help.
