### ISSUE TITLE
Icons in buttons misaligned and too big

### ISSUE THREAD

**Issue by locobert** [stasson/vue-mdc-adapter#340]
Codepen <https://codepen.io/anon/pen/NYaZbw>
Tested with Chrome and Firefox.

I am using examples from the vue-mdc and the mdc websites, i.e.,

```html
<mdc-button><mdc-icon icon="favorite"></mdc-icon>vue-mdc</mdc-button>
```
and
```html
<button class="mdc-button"><i class="material-icons mdc-button__icon">favorite</i>pure-mdc</button>
```

With the Chrome dev tools, the icon part of the vue version looks as follows
```html
<span class="mdc-icon mdc-icon--material material-icons">favorite</span>
```
and of the pure version as
```html
<i class="material-icons mdc-button__icon">favorite</i>
```

Using the Chrome devtools for the vue version, I've replaced `mdc-icon--material` with `mdc-button__icon` in the class attribute and it looks OK (see "hacked-vue-mdc" in the codepen):
```html
<span class="mdc-icon mdc-button__icon material-icons">favorite</span>
```

**Comment by pgbross** [comment]
Looking at the underlying `MDC button` component it allows for an icon to be added by nesting an element with `mdc-button__icon`. The examples in the [docs](https://github.com/material-components/material-components-web/tree/master/packages/mdc-button) show both how to use [Material Icons](https://material.io/icons/) and an SVG icon, and by extension one could presumably add custom markup to use a different font library or otherwise.

The `vue-mdc-adapter` component `mdc-icon` is not exclusively for adding an icon to a button, but can be rendered as needed. It is also opinionated and rightly or wrongly sets the font-size (24px) and line-height (1), which is unsuitable for a button.

So the following markup renders correctly:
```
<mdc-button>
  <i class="material-icons mdc-button__icon">favorite</i>
  Button
</mdc-button>
```

The question is should there be a `mdc-button-icon` component, and what purpose would it solve? 

One problem is that Vue components generally need to render to a single root node (element) so needs to know if it is rendering an `<i />` or `<svg />` or something else or emit a wrapper element. But emitting a wrapper element could then upset the rendering due to the html structure not being what was expected by the `material-components-web` designers (or it becomes biased towards material icons without considering font-awesome/svg etc). You would also still have to have a mechanism for choosing to render a [Material Icons](https://material.io/icons/) icon or some custom markup.

It seems that creating an `mdc-button-icon` might mean more verbose markup to set options and select the kind of element to produce than simply entering the plain html as the above example. In any particular project as opposed to a library, one could easily create a custom component according to its specific requirements, because the decision to use Material Icons or otherwise has been taken.

At this stage, therefore, I think we should update the documentation to avoid using `mdc-icon` in button markup. Having experimented a little I do not think we should introduce a new component (mdc-button-icon) that is neither wrapping a native element or managing more complicated behaviour.

**Comment by locobert** [comment]
Thank you for your investigation and the quick feedback! I am happy with adding the explicit markup.

Just to add a learner's perspective: my expectation would be to have an optional icon attribute for `mdc-button`, similarly to [mdc-tab](https://stasson.github.io/vue-mdc-adapter/#/component/tabs) 
```html
<mdc-tab-bar>
  <mdc-tab icon="phone"></mdc-tab>
  <mdc-tab icon="{className: 'fa fa-favorite'}"></mdc-tab>
  <mdc-tab><svg slot="icon">...</svg></mdc-tab>
</mdc-tab-bar>
```
Of course the gain in convenience is certainly slanted towards Material Icons and I have no idea, how much complexity this would add to the button class, for handling something that is not the common use case.

**Comment by pgbross** [comment]
I thought about adding an optional icon attribute, but then even that got complicated because it could be a leading icon or a trailing icon or both, or even multiple icons!

Anyway glad you are happy with the explicit markup for now.
