### ISSUE TITLE
Buttons have different behavior than original

### ISSUE THREAD

**Issue by iamdubx** [stasson/vue-mdc-adapter#48]
Hello. Nice to see work on this wrapper is in process. Great plugin for Vue!

I notice, that Buttons have different behavior than original. If you quickly click on them, this one doesn't trigger ripple effect. 

Original - https://material-components-web.appspot.com/button.html

**Comment by stasson** [comment]
@iamdubx 

Hello, 

Thanks for the feedback.

I guess the difference comes from how Vue's triggers DOM update. I may need to bypass Vue's queue and do direct DOM update for the ripple in order to get te exact same behaviour.  

On my setup, I can see a small difference. May be I am under estimating the issue though and you really have a sluggish experience on your setup? can you provide some more details (may be a short video capture ?)  

For now the difference I see is not big enough to take care of this right now. There is still some important refactoring I need to do before having a proper beta version... So I'll keep this one a medium priority.

**Comment by stasson** [comment]
@iamdubx 

Well actually I have just tested on another setup and I can see it clearly now....
I need to investigate this more...

**Comment by iamdubx** [comment]
@stasson thanks for feedback!
So you notice issue? If you click multiple times, ripple doesn't trigger. I can capture it, if needed.

**Comment by stasson** [comment]
@iamdubx 

yes I noticed the issue. no need to capture... the ripple is triggered on first click, but if you are fast enough it's like the button doesn't have the time to release. 
I actually like this behavior better than the MDC demo site... and I'd hate to have to bypass vue's dom update caching... I need to investigate further ...
