### ISSUE TITLE
Outlined textfield broken with most current builds of @material/textfield

### ISSUE THREAD

**Issue by maiorano84** [stasson/vue-mdc-adapter#566]
### What vue-mdc-adapter Version are you using?
2.5.21

### What browser(s) is this bug affecting?
All browsers, all operating systems

### What are the steps to reproduce the bug?
1. `git clone git@github.com:maiorano84/vue-mdc-bug.git mdc && cd mdc && npm install`
2. `npm run serve`
3. Navigate to http://localhost:8080
4. Click on the text field and observe what happens

### What is the expected behavior?
An outline should be visible, and all textfields and notch components should respond on focus

### What is the actual behavior?
A solid black SVG obscures the component

### Any other information you believe would be useful?
The latest version of @material/textfield and @material/notched-outline switched from an SVG path to three separate divs. All styles associated with this path have been removed in the latest source SCSS files.

Removal of the SVG element in the `components/textfield/mdc-textfield.vue` file and replacing it with the updated format [outlined here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield#outlined) should resolve the root of the issue.

Because the label element now appears within the notched divs, an extra boolean check will have to be made on the first label element:

```
<label
        v-if="hasLabel && !hasOutline"
        ref="label"
        :class="labelClassesUpgraded"
        :for="vma_uid_">
        {{ label }}
</label>
```

The notched outline block may then use something like the following (untested):

```
<div
        v-if="hasOutline"
        ref="outline"
        :class="outlineClasses"
        class="mdc-notched-outline">
    <div class="mdc-notched-outline__leading"></div>
    <div class="mdc-notched-outline__notch">
      <label
        v-if="hasLabel && hasOutline"
        ref="label"
        :class="labelClassesUpgraded"
        :for="vma_uid_">
        {{ label }}
      </label>
    </div>
    <div class="mdc-notched-outline__trailing"></div>
</div>
```

It is also likely that the current instance of the `MDCNotchedOutlineFoundation` class will need to be updated.

**Comment by kieryk123** [comment]
same here +1, I have spent the whole day to fix it...

**Comment by maiorano84** [comment]
@kieryk123 It looks like this project has been abandoned and is almost completely broken with the latest versions of MDC Web. If you value your time, I would highly recommend finding a different package or forking this one.

**Comment by pgbross** [comment]
I forked this package and have made [vue-material-adapter](https://github.com/pgbross/vue-material-adapter) that uses the current material-components-web (v1.1.0) framework. There are a number of breaking changes, primarily because of the changes in `material-components-web`, but it is fairly compatible otherwise. The biggest thing that is missing is up to date documentation as until recently this was just me keeping up to date for my own use and I haven't had the cycles to get to updating the docs. 

The other visible change is in how the project is structured - it now is a "monorepo" along the lines of the `material-components-web-react `project (as this seems more common nowadays and allows me to reuse their scripts and processes to some extent).
