### ISSUE TITLE
fix documentation spelling/english issues

### ISSUE THREAD

**Issue by stasson** [stasson/vue-mdc-adapter#89]

**Comment by stasson** [comment]
having the help from an native english speaker would be nice

**Comment by griest024** [comment]
@stasson I am a native english speaker. Which docs are you concerned about?

**Comment by griest024** [comment]
@stasson For future reference, here are some of the recurring problems I found:

- Misspelling property as propertie
- Misspelling whether as wether
- Using may instead of might (may is used for permission, might indicates possibility)
- Misspelling emitted as emited
- Generally using too many commas

To be fair, many native speakers often confuse may with might and use too many commas. [This webpage](http://pages.uoregon.edu/munno/Writing/ClausesandCommas.html) describes when to break up a sentence using a comma.
