### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by griest024** [stasson/vue-mdc-adapter#9]
We need some unit tests. I think the file structure for `test/unit/specs` should mirror that of `src/components`. So the test for `src/components/[component-group]/mdc-[component].vue` would be `test/unit/specs/[component-group]/mdc-[component].spec.js`

**Comment by stasson** [comment]
agreed on the structure. I have not started Unit Test yet, mostly because  I don't know how karma/mocha works yet. but it'll be a must have before RC candidate so that we can update dependencies to MDC safely.
I wanted to finish a first draft of each components and go through one full review/refactoring first and then I guess unit doc and UT will be the step...

**Comment by stasson** [comment]
plan is to deploy tests with jest
- need UT to validate foundation adapter's api
- need UT to validate component APIs

**Comment by stasson** [comment]
npm run test merged in v0.0.49
